make_mults <- function(impbridge, costf, mults, type, sector, ticsin, ecpi,
    taxes, comnamesin = NULL, output = NULL, zeroprop = TRUE, zeropropdir = FALSE,
    agg_level = "commodity") {
  #' Create IOPAC multipliers
  #'
  #' A unified function that creates impact multipliers for either commodity or vessel level
  #'
  #' @param impbridge Commodity flows data from IMPLAN
  #' @param costf Cost data from NWFSC surveys
  #' @param mults Output, income, and employment multipliers from IMPLAN
  #' @param type String. Type of output ("output", "employment", or "income")
  #' @param sector String. Commodity type
  #' @param ticsin Fish tickets by revenue from PACFIN
  #' @param ecpi Multipliers for employee compensation and proprietary income
  #' @param taxes Multipliers for induced effects from taxes
  #' @param comnamesin Common names (for commodity level aggregation)
  #' @param output Type of output (legacy parameter)
  #' @param zeroprop Logical. Whether to zero negative proprietary income
  #' @param zeropropdir Logical. Whether to zero negative proprietary income in direct effects
  #' @param agg_level "commodity" for commodity-level or "vessel" for vessel-level aggregation
  #' @return Multipliers appropriate to the aggregation level
  #' @export

  # A. Setup IMPLAN Bridge
  impbridge$ID <- seq_len(nrow(impbridge))

  # B. Costs mapped to IMPLAN categories
  costmult <- merge(impbridge[c("ID", "Type", if(agg_level == "commodity") "CommodityCode")],
    costf, by = c("Type"), all.x = TRUE, all.y = FALSE)
  costmult <- costmult[order(costmult$ID), ]

  mprod <- costmult[, !names(costmult) %in% c("ID", "Type", "Cost", "CommodityCode")]
  mprod <- mprod * impbridge$Share

  # C. Hypothetical impact
  impact <- 1

  # D. Lookup multipliers by category
  lookmult <- merge(impbridge[c("ID", "CommodityCode")], mults,
    by = c("CommodityCode"), all.x = TRUE, all.y = FALSE, sort = FALSE)
  lookmult <- lookmult[order(lookmult$ID), ]

  # E. Impacts generated by expenditures
  if (agg_level == "commodity") {
    inteff_raw <- mprod[, !names(mprod) %in% c("ID", "Type", "Cost", "CommodityCode")] *
      impact * as.matrix(lookmult[sector])
    inteff_raw[is.na(inteff_raw)] <- 0

    inteff <- cbind(CommodityCode = lookmult$CommodityCode, inteff_raw)
    inteffagg <- aggregate(inteff[, -1],
      by = list(CommodityCode = inteff$CommodityCode), FUN = sum)
  } else {
    inteff <- colSums(mprod * impact * as.matrix(lookmult[sector]), na.rm = TRUE)
  }

  # F. Employee compensation impacts
  empcomp <- colSums(as.data.frame(costf[costf$Type %in% c("Captain", "Crew"),
    !names(costf) %in% c("ID", "Type", "Cost")])) * impact *
    ecpi[ecpi$Type == paste0("EmpComp", type), c(sector)]

  # G. Proprietary income impacts
  if (zeroprop == TRUE) {
    costftemp <- costf
    costftemp[costftemp$Type %in% c("Proprietary income"),
      !names(costftemp) %in% c("ID", "Type", "Cost")][
      costftemp[costftemp$Type %in% c("Proprietary income"),
        !names(costftemp) %in% c("ID", "Type", "Cost")] < 0] <- 0
    propType <- "costftemp"
  } else {
    costftemp <- costf
    propType <- "costf"
  }

  propinc <- colSums(as.data.frame(get(propType)[get(propType)$Type %in%
    c("Purchases of permits", "Leasing of permits", "Proprietary income"),
    !names(get(propType)) %in% c("ID", "Type", "Cost")])) * impact *
    ecpi[ecpi$Type == paste0("PropInc", type), c(sector)]

  # H. Tax impacts
  looktaxes <- colSums(as.data.frame(costf[costf$Type %in% c("Landings Taxes"),
    !names(costf) %in% c("ID", "Type", "Cost")])) * impact *
    taxes[taxes$Type == type, sector]
  if (length(looktaxes) == 0) looktaxes <- 0

  # I. Aggregation level specific calculations
  if (agg_level == "commodity") {
    # Add rows to inteffagg for each impact type
    empcomp_row <- data.frame(CommodityCode = "EmpComp",
      as.data.frame(as.list(empcomp)))
    inteffagg <- rbind(inteffagg, empcomp_row)

    looktaxes_row <- data.frame(CommodityCode = "LookTaxes",
      as.data.frame(as.list(looktaxes)))
    inteffagg <- rbind(inteffagg, looktaxes_row)

    propinc_row <- data.frame(CommodityCode = "PropInc",
      as.data.frame(as.list(propinc)))
    inteffagg <- rbind(inteffagg, propinc_row)

    if (type == "Output") {
      direct_row <- data.frame(CommodityCode = "DirOut",
        as.data.frame(as.list(rep(impact, ncol(inteffagg) - 1))))
      colnames(direct_row)[-1] <- colnames(inteffagg)[-1]
      inteffagg <- rbind(inteffagg, direct_row)
    } else if (type == "Income") {
      if (zeropropdir == TRUE) {
        costftemp <- costf
        costftemp[costftemp$Type %in% c("Proprietary income"),
          !names(costftemp) %in% c("ID", "Type", "Cost")][
          costftemp[costftemp$Type %in% c("Proprietary income"),
            !names(costftemp) %in% c("ID", "Type", "Cost")] < 0] <- 0
        dirincType <- "costftemp"
      } else {
        dirincType <- "costf"
      }

      dirinc <- colSums(as.data.frame(get(dirincType)[get(dirincType)$Type %in%
        c("Captain", "Crew", "Purchases of permits", "Leasing of permits",
          "Proprietary income"),
        !names(get(dirincType)) %in% c("ID", "Type", "Cost")])) * impact

      dirinc_row <- data.frame(CommodityCode = "DirInc",
        as.data.frame(as.list(dirinc)))
      inteffagg <- rbind(inteffagg, dirinc_row)
    } else if (type == "Employment") {
      diremp <- as.numeric(impact / (as.data.frame(costf[costf$Type %in%
        c("Output per Employee"), !names(costf) %in% c("ID", "Type", "Cost")])))
      diremp[is.infinite(diremp)] <- NaN

      diremp_row <- data.frame(CommodityCode = "DirEmp",
        as.data.frame(as.list(diremp)))
      inteffagg <- rbind(inteffagg, diremp_row)
    }

    # Create weighted output matrix
    ticsprop <- ticsin[-1] / replicate(nrow(ticsin[-1]), rowSums(ticsin[-1]))
    output <- matrix(NA, nrow = nrow(ticsprop), ncol = nrow(inteffagg))
    colnames(output) <- inteffagg$CommodityCode

    for (i in 1:nrow(ticsprop)) {
      weights <- as.numeric(ticsprop[i, ])
      if (all(is.na(weights))) {
        output[i, ] <- NA
      } else {
        weights[is.na(weights)] <- 0
        output[i, ] <- as.matrix(inteffagg[, -1]) %*% weights
      }
    }

    output <- as.data.frame(output)
    rownames(output) <- comnamesin$Name
    return(output)

  } else {
    # Vessel level: compute direct effects and divide by impact
    if (type == "Output") {
      sumdirect <- inteff + empcomp + propinc + looktaxes + impact
    } else if (type == "Income") {
      if (zeropropdir == TRUE) {
        costftemp <- costf
        costftemp[costftemp$Type %in% c("Proprietary income"),
          !names(costftemp) %in% c("ID", "Type", "Cost")][
          costftemp[costftemp$Type %in% c("Proprietary income"),
            !names(costftemp) %in% c("ID", "Type", "Cost")] < 0] <- 0
        dirincType <- "costftemp"
      } else {
        dirincType <- "costf"
      }

      dirinc <- colSums(as.data.frame(get(dirincType)[get(dirincType)$Type %in%
        c("Captain", "Crew", "Purchases of permits", "Leasing of permits",
          "Proprietary income"),
        !names(get(dirincType)) %in% c("ID", "Type", "Cost")])) * impact

      sumdirect <- inteff + empcomp + propinc + looktaxes + dirinc
    } else if (type == "Employment") {
      diremp <- as.numeric(impact / (as.data.frame(costf[costf$Type %in%
        c("Output per Employee"), !names(costf) %in% c("ID", "Type", "Cost")])))
      diremp[is.infinite(diremp)] <- NaN
      sumdirect <- inteff + empcomp + propinc + looktaxes + diremp
    }

    mults <- sumdirect / impact

    # Fleet-level multipliers
    ticsprop <- ticsin[-1] / replicate(nrow(ticsin[-1]), rowSums(ticsin[-1]))
    output <- as.matrix(mults) %*% as.matrix(t(ticsprop))
    return(as.numeric(output))
  }
}

# Wrapper functions for backward compatibility
make_cat_mults <- function(impbridge = impbridgelist[["vessel"]],
  costf = costfin[["vessel"]], mults = multsin[["Output"]], type = "Output",
  sector = "Oregon", ticsin = ticsin[["Oregon"]], ecpi = ecpiin,
  taxes = taxesin, comnamesin = comnames, output = NULL, zeroprop = TRUE,
  zeropropdir = FALSE) {
  make_mults(impbridge, costf, mults, type, sector, ticsin, ecpi, taxes,
    comnamesin, output, zeroprop, zeropropdir, agg_level = "commodity")
}

make_v_mults <- function(impbridge, costf, mults, type, sector, ticsin, ecpi,
  taxes, output = NULL, zeroprop = TRUE, zeropropdir = FALSE) {
  make_mults(impbridge, costf, mults, type, sector, ticsin, ecpi, taxes,
    comnamesin = NULL, output, zeroprop, zeropropdir, agg_level = "vessel")
}
