make_p_cat_mults <- function(impbridge = impbridgelist,
  costf = costfin,
  mults = multsin,
  type = "Output",
  sector = "Oregon",
  ticsin = ticsin,
  ecpi = ecpiin,
  taxes = taxesin,
  prodflow = prodflow,
  markups = markups_list$y2023,
  fskey = fskey,
  comnamesin = comnames) {

    #' Create IOPAC processor commodity multipliers
    #'
    #' A function that creates commodity-level impact multipliers for processors
    #'
    #' @param impbridge Commodity flows data from IMPLAN
    #' @param costf Cost data from NWFSC surveys for processors
    #' @param mults Output, income, and employment multipliers from IMPLAN
    #' @param type String. Type of output ("output", "employment", or "income")
    #' @param sector String. Commodity type
    #' @param ticsin Fish tickets by revenue from PACFIN
    #' @param ecpi Multipliers for employee compensation and proprietary income
    #' @param taxes Multipliers for induced effects from taxes
    #' @param prodflow A data frame denoting product flow
    #' @param markups Processor markups from NWFSC data
    #' @param fskey A data frame denoting the relationship between species, commodities, and gear types
    #' @param comnamesin Common names for output row names
    #' @return A data frame with commodity codes and impact multipliers
    #' @export

  impbridge <- impbridge[["processor"]]
  costf <- costf[["processor"]]
  ticsin <- ticsin[[sector]]
  mults <- mults[[type]]

  # A. IMPLAN Bridge
  impbridge$ID <- seq_len(nrow(impbridge))
  options(stringsAsFactors = FALSE)

  # B. Setup for commodity-level aggregation
  impbridge$CommodityCode <- mults$CommodityCode[
    match(impbridge$CommodityCode, mults$CommodityCode)]

  # C. Costs mapped to IMPLAN categories
  prodf <- merge(impbridge[c("ID", "Type", "Share", "CommodityCode")],
      costf[c("Type", "Value", "ShareC")], by = c("Type"), all.x = TRUE)

  # Set Share to 0 if Fish purchases
  prodf[prodf$Type == 'Fish purchases', "Share"] <- 0

  # Zero out manual exclusions
  prodf[prodf$Type ==
    'Rental or lease of buildings, job-site trailers, and other structures',
      c("Value", "ShareC")] <- 0
  prodf <- prodf[order(prodf$ID), ]

  # D. Lookup to join multipliers by category
  lookmult <- merge(impbridge[c("ID", "CommodityCode")], mults,
      by = c("CommodityCode"), all.x = TRUE, all.y = FALSE, sort = FALSE)
  lookmult <- lookmult[order(lookmult$ID), ]

  # E. Cost categories weighted by share of total cost
  mapprod <- prodf$Share * prodf$ShareC

  # F. Hypothetical impact
  impact <- 1

  # G. Impacts generated by all expenditures (except wages/prop inc)
  inteff_raw <- mapprod * impact * as.matrix(lookmult[sector])
  inteff_raw[is.na(inteff_raw)] <- 0

  # Aggregate by CommodityCode
  inteff <- data.frame(cbind(
    CommodityCode = lookmult$CommodityCode,
    inteff_raw
  ))

  inteffagg <- aggregate(inteff[, -1],
    by = list(CommodityCode = inteff$CommodityCode), FUN = sum)

  # H. Calculate indirect impacts from EC
  empcomp <- impact *
      costf$ShareC[costf$Type == "Employee and Worker Payroll"] *
      ecpi[ecpi$Type == paste0("EmpComp", type), c(sector)]

  # Add empcomp as a row
  empcomp_row <- data.frame(
    CommodityCode = "EmpComp",
    as.data.frame(as.list(empcomp))
  )

  colnames(empcomp_row)[-1] <- colnames(inteffagg)[-1]
  inteffagg <- rbind(inteffagg, empcomp_row)

  # I. Calculate indirect impacts from PI
  propinc <- impact *
      costf$ShareC[costf$Type == "Proprietary Income"] *
      ecpi[ecpi$Type == paste0("PropInc", type), c(sector)]

  # Add propinc as a row
  propinc_row <- data.frame(
    CommodityCode = "PropInc",
    as.data.frame(as.list(propinc))
  )
  colnames(propinc_row)[-1] <- colnames(inteffagg)[-1]
  inteffagg <- rbind(inteffagg, propinc_row)

  # J. Calculate indirect impacts from taxes/license fees
  looktaxes <- impact *
      sum(costf$ShareC[costf$Type %in% c("Licensing Fees", "Taxes")]) *
      taxes[taxes$Type == type, sector]
  if (length(looktaxes) == 0) {
      looktaxes <- 0
  }

  # Add looktaxes as a row
  looktaxes_row <- data.frame(
    CommodityCode = "Taxes",
    as.data.frame(as.list(looktaxes))
  )
  colnames(looktaxes_row)[-1] <- colnames(inteffagg)[-1]
  inteffagg <- rbind(inteffagg, looktaxes_row)

  # K. Direct effects based on type
  if (type == "Output") {
    direct_row <- data.frame(
      CommodityCode = "DirOut",
      as.data.frame(as.list(rep(impact, ncol(inteffagg) - 1)))
    )
    colnames(direct_row)[-1] <- colnames(inteffagg)[-1]
    inteffagg <- rbind(inteffagg, direct_row)

  } else if (type == "Income") {
    dirinc <- sum(costf$ShareC[costf$Type %in%
        c("Employee and Worker Payroll", "Proprietary Income")]) * impact

    dirinc_row <- data.frame(
      CommodityCode = "DirInc",
      as.data.frame(as.list(rep(dirinc, ncol(inteffagg) - 1)))
    )
    colnames(dirinc_row)[-1] <- colnames(inteffagg)[-1]
    inteffagg <- rbind(inteffagg, dirinc_row)

  } else if (type == "Employment") {
    diremp <- impact / costf$Value[costf$Type == "Output per Employee"]

    diremp_row <- data.frame(
      CommodityCode = "DirEmp",
      as.data.frame(as.list(rep(diremp, ncol(inteffagg) - 1)))
    )
    colnames(diremp_row)[-1] <- colnames(inteffagg)[-1]
    inteffagg <- rbind(inteffagg, diremp_row)
  }

  prodflow$Share <- prodflow$Processor.demand/prodflow$Total.Supply
  prodflow$Share[prodflow$Share > 1] <- 1.00

  fskey$ID <- seq_len(nrow(fskey))

  # L. Create weighted impact output
  ticsprop <- ticsin[-1] / replicate(nrow(ticsin[-1]), rowSums(ticsin[-1]))

  # P. Markups to rescale the fish purchase info -> production value
  markups$procrev <- markups$Value*
      impact*
      c(rep(prodflow$Share[prodflow$Region == sector], 10))

  markups$procrevspecial <- markups$procrev
  markups$procrevspecial[markups$Markups %in% 
      c("Whiting", "Sablefish", "Dover/thornyhead", "Other groundfish")] <-
    markups$Value[markups$Markups %in% 
      c("Whiting", "Sablefish", "Dover/thornyhead", "Other groundfish")]*impact*1

  # Q. Production revenue for a given impact
  procrev <- merge(fskey, markups, by = c("Markups"), all.x = TRUE,
    sort = FALSE)
  procrev <- procrev[order(procrev$ID), ]

  output <- matrix(NA, nrow = nrow(ticsprop), ncol = nrow(inteffagg))
  colnames(output) <- inteffagg$CommodityCode
  rownames(output) <- comnamesin$Name

  for (j in 1:nrow(inteffagg)) {

  mults <- inteffagg[j,2]

  # #are there always only 10 species?
  if (sector == "WC" || sector == "Washington" || sector == "California" ||
      sector == "Oregon") {
  # R. Get fleet-level multipliers based on fish tickets
  procrevmult <- cbind(replicate(4, (procrev$procrevspecial*mults)/impact),
      replicate((dim(ticsprop)[2] - 4), (procrev$procrev*mults)/impact))

  } else {

  procrevmult <- replicate(dim(ticsprop)[2], (procrev$procrev*mults)/impact)

  }

  #drop last four rows because they're calculated below, different aggregation
  procoutcoef <- rowSums(ticsprop[1:(nrow(ticsprop) - 4), ]*procrevmult,
    na.rm = TRUE)

  fskeytemp <- cbind(fskey, procoutcoef)

  # Calculate averages for each gear type, handling all NA cases
  calc_avg <- function(x, fskeytemp) {
    vals <- fskeytemp$procoutcoef[fskeytemp[, x] == 1]
    if (all(is.na(vals))) NaN else mean(vals, na.rm = TRUE)
  }

  # Check last four rows of ticsprop, set trawlavg, fgavg, netavg, othavg to NaN if their row is all NaN
  last4 <- as.matrix(ticsprop[(nrow(ticsprop)-3):nrow(ticsprop), ])

  trawlavg <- if (all(is.nan(last4[1, ]))) NaN else calc_avg("Trawl", fskeytemp)
  fgavg    <- if (all(is.nan(last4[2, ]))) NaN else calc_avg("FG", fskeytemp)
  netavg   <- if (all(is.nan(last4[3, ]))) NaN else calc_avg("Net", fskeytemp)
  othavg   <- if (all(is.nan(last4[4, ]))) NaN else calc_avg("Other", fskeytemp)

  #calculate last four rows (Erin can ignore this step)
  procoutcoefout <- c(procoutcoef, trawlavg, fgavg, netavg, othavg)

  output[, j] <- procoutcoefout

  }

  output <- as.data.frame(output)
  return(output)

}
