make_v_cat_mults <- function(impbridge = impbridgelist,
  costf = costfin,
  mults = multsin,
  type = "Output",
  sector = "Oregon",
  ticsin = ticsin,
  ecpi = ecpiin,
  taxes = taxesin,
  comnamesin = comnames,
  output = NULL,
  zeroprop = TRUE,
  zeropropdir = FALSE) {

  impbridge <- impbridge[["vessel"]]
  costf <- costf[["vessel"]]
  ticsin <- ticsin[[sector]]
  mults <- mults[[type]]

  impbridge$ID <- seq_len(nrow(impbridge))
  costmult <- merge(impbridge[c("ID", "Type", "CommodityCode")], costf,
    by = c("Type"), all.x = TRUE, all.y = FALSE)
  costmult <- costmult[order(costmult$ID), ]
  mprod <- costmult
  mprod[, !names(mprod) %in% c("ID", "Type", "Cost", "CommodityCode")] <-
    costmult[, !names(costmult) %in%
    c("ID", "Type", "Cost", "CommodityCode")] * impbridge$Share

  # C. Hypothetical impact that gets cancelled out at the end
  impact <- 1
  # D. Lookup to join multipliers by category
  lookmult <- merge(impbridge[c("ID", "CommodityCode")], mults,
    by = c("CommodityCode"), all.x=TRUE, all.y = FALSE, sort = FALSE)
  lookmult <- lookmult[order(lookmult$ID), ]

  # E. Impacts generated by all expenditures (except wages/prop inc)
  # Grab correct region (Sector) here
  inteff_raw <- mprod[, !names(mprod) %in%
    c("ID", "Type", "Cost", "CommodityCode")]*impact*as.matrix(lookmult[sector])
  inteff_raw[is.na(inteff_raw)] <- 0

  # Aggregate by CommodityCode: 183 unique codes x 18 impact columns
  inteff <- cbind(
    CommodityCode = lookmult$CommodityCode,
    inteff_raw
  )

  #note commoditycode order changes here
  inteffagg <- aggregate(inteff[, -1],
    by = list(CommodityCode = inteff$CommodityCode), FUN = sum)

  # F. Calculate indirect impacts from EC
  empcomp <- colSums(as.data.frame(costf[costf$Type %in% c("Captain", "Crew"),
      !names(costf) %in% c("ID", "Type", "Cost")]))*impact*
      ecpi[ecpi$Type == paste0("EmpComp", type), c(sector)]

  # Add empcomp as a row in inteffagg
  empcomp_row <- data.frame(
    CommodityCode = "EmpComp",
    as.data.frame(as.list(empcomp))
  )
  inteffagg <- rbind(inteffagg, empcomp_row)

  # H. Calculate indirect impacts from taxes/license fees
  looktaxes <- colSums(as.data.frame(costf[costf$Type %in% c("Landings Taxes"),
      !names(costf) %in% c("ID", "Type", "Cost")]))*impact*
      taxes[taxes$Type == type, sector]
  if (length(looktaxes) == 0) {
      looktaxes <- 0
  }

  # Add looktaxes as a row in inteffagg
  looktaxes_row <- data.frame(
    CommodityCode = "Taxes",
    as.data.frame(as.list(looktaxes))
  )
  inteffagg <- rbind(inteffagg, looktaxes_row)

  if(zeroprop == TRUE){
  costftemp <- costf

  costftemp[costftemp$Type %in% c("Proprietary income"),
    !names(costftemp) %in% c("ID", "Type", "Cost")][
      costftemp[costftemp$Type %in% c("Proprietary income"),
      !names(costftemp) %in% c("ID", "Type", "Cost")] < 0] <- 0

  propinc <- colSums(as.data.frame(costftemp[costftemp$Type %in%
    c("Purchases of permits", "Leasing of permits", "Proprietary income"),
      !names(costftemp) %in% c("ID", "Type", "Cost")]))*impact*
      ecpi[ecpi$Type == paste0("PropInc", type), c(sector)]

  } else {
  # G. Calculate indirect impacts from PI
  propinc <- colSums(as.data.frame(costf[costf$Type %in% c("Purchases of permits",
          "Leasing of permits", "Proprietary income"),
      !names(costf) %in% c("ID", "Type", "Cost")]))*impact*
      ecpi[ecpi$Type == paste0("PropInc", type), c(sector)]
  }

  propinc_row <- data.frame(
    CommodityCode = "PropInc",
    as.data.frame(as.list(propinc))
  )
  inteffagg <- rbind(inteffagg, propinc_row)

  if (type == "Output") {

  direct_row <- data.frame(
    CommodityCode = "DirOut",
    as.data.frame(as.list(rep(impact, ncol(inteffagg)-1)))
  )
  colnames(direct_row)[-1] <- colnames(inteffagg)[-1]
  inteffagg <- rbind(inteffagg, direct_row)

  } else if (type == "Income") {

  if(zeropropdir == TRUE){
  costftemp <- costf

  costftemp[costftemp$Type %in% c("Proprietary income"),
    !names(costftemp) %in% c("ID", "Type", "Cost")][
      costftemp[costftemp$Type %in% c("Proprietary income"),
      !names(costftemp) %in% c("ID", "Type", "Cost")] < 0] <- 0

  dirinc <- colSums(as.data.frame(costftemp[costftemp$Type %in% c("Captain",
    "Crew", "Purchases of permits", "Leasing of permits", "Proprietary income"),
      !names(costftemp) %in% c("ID", "Type", "Cost")]))*impact
  } else {
  dirinc <- colSums(as.data.frame(costf[costf$Type %in% c("Captain", "Crew",
    "Purchases of permits", "Leasing of permits", "Proprietary income"),
      !names(costf) %in% c("ID", "Type", "Cost")]))*impact
  }

  dirinc_row <- data.frame(
    CommodityCode = "DirInc",
    as.data.frame(as.list(dirinc))
  )
  inteffagg <- rbind(inteffagg, dirinc_row)

  } else if (type == "Employment") {

  diremp <- as.numeric(impact/(as.data.frame(costf[costf$Type %in% c(
    "Output per Employee"), !names(costf) %in% c("ID", "Type", "Cost")])))
  diremp[is.infinite(diremp)] <- NaN

  diremp_row <- data.frame(
    CommodityCode = "DirEmp",
    as.data.frame(as.list(diremp))
  )

  colnames(diremp_row)[-1] <- colnames(inteffagg)[-1]
  inteffagg <- rbind(inteffagg, diremp_row)

  }

  ticsprop <- ticsin[-1]/replicate(nrow(ticsin[-1]), rowSums(ticsin[-1]))

  # Create weighted impact output: 32 rows (from ticsprop) x 183 CommodityCode
  output <- matrix(NA, nrow = nrow(ticsprop), ncol = nrow(inteffagg))
  colnames(output) <- inteffagg$CommodityCode

  for(i in 1:nrow(ticsprop)) {
    weights <- as.numeric(ticsprop[i, ])
    if(all(is.na(weights))) {
      output[i, ] <- NA
    } else {
      weights[is.na(weights)] <- 0
      output[i, ] <- as.matrix(inteffagg[, -1]) %*% weights
    }
  }

  output <- as.data.frame(output)
  rownames(output) <- comnamesin$Name

  return(output)
}
